bfactor:
	ghc -o ../lib/pt_bfactor bfactor.hs 
	rm *.hi 
	rm *.o
fasta:
	ghc -O2 --make fasta.hs -o ../lib/fasta
	rm *.hi 
	rm *.o
fasta2csv:
	ghc -O2 --make fasta2csv.hs -o ../lib/fasta2csv
	rm *.hi 
	rm *.o 